["scoop/persist/firefox-developer/profile/chrome"]
type = "git-repo"
url = "https://github.com/KiKaraage/ArcWTF.git"
refreshPeriod = "168h"

[".config/nvim"]
type = "git-repo"
url = "git@github.com:noidilin/nvim.git"
refreshPeriod = "168h"

[".config/yazi/flavors/color-fatigue.yazi"]
type = "git-repo"
url = "https://github.com/noidilin/color-fatigue.yazi.git"
refreshPeriod = "168h"

[".config/wezterm"]
type = "git-repo"
url = "https://github.com/noidilin/wezterm.git"
refreshPeriod = "168h"

[".config/cursor"]
type = "git-repo"
url = "https://github.com/YT-Advanced/Windows-11-Cursor-by-rosea92.git"
refreshPeriod = "168h"

# [".config/windows-terminal/windows-terminal-shaders"]
# type = "git-repo"
# url = "https://github.com/Hammster/windows-terminal-shaders.git"
# refreshPeriod = "168h"

# [".githelpers"]
# type = "file"
# url = "https://raw.githubusercontent.com/stevearc/dotfiles/master/.githelpers"
# refreshPeriod = "168h"

# [".config/yazi/theme.toml"]
# type = "file"
# url = "https://raw.githubusercontent.com/catppuccin/yazi/main/themes/mocha.toml"
# refreshPeriod = "168h"

# [".config/yazi/Catppuccin-mocha.tmTheme"]
# type = "file"
# url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
# refreshPeriod = "168h"

# ["AppData/Roaming/bat/themes/Catppuccin Mocha.tmTheme"]
# type = "file"
# url = "https://raw.githubusercontent.com/catppuccin/bat/main/themes/Catppuccin%20Mocha.tmTheme"
# refreshPeriod = "168h"

# ["Documents/PowerShell/Modules/Catppuccin"]
# type = "git-repo"
# url = "https://github.com/catppuccin/powershell.git"
# refreshPeriod = "168h"
#
# [".config/delta/themes/catppuccin"]
# type = "git-repo"
# url = "https://github.com/catppuccin/delta.git"
# refreshPeriod = "168h"

# ["AppData/Local/glow/Config/themes/catppuccin-mocha.json"]
# type = "file"
# url = "https://raw.githubusercontent.com/catppuccin/glamour/main/themes/catppuccin-mocha.json"
# refreshPeriod = "168h"

# [".config/qbittorrent/themes/catppuccin-mocha.qbtheme"]
# type = "file"
# url = "https://github.com/catppuccin/qbittorrent/raw/main/mocha.qbtheme"
# refreshPeriod = "168h"
