# Theme create by: https://github.com/AnshumanNeon
# Update by(sort by time):
#
# Thanks for all contributor!!

# If you want to make sidebar border display just set it same as sidebar background color

# Code syntax highlight theme (you can go to https://github.com/alecthomas/chroma/blob/master/styles to find one you like)
code_syntax_highlight = "algol"

# ========= Border =========
file_panel_border = "#414141"
sidebar_border = "#414141"
footer_border = "#414141"

# ========= Border Active =========
file_panel_border_active = "#5d5d5d"
sidebar_border_active = "#5d5d5d"
footer_border_active = "#5d5d5d"
modal_border_active = "#5d5d5d"

# ========= Background (bg) =========
full_screen_bg = "#191919"
file_panel_bg = "#191919"
sidebar_bg = "#191919"
footer_bg = "#191919"
modal_bg = "#191919"

# ========= Foreground (fg) =========
full_screen_fg = "#878787"
file_panel_fg = "#878787"
sidebar_fg = "#878787"
footer_fg = "#878787"
modal_fg = "#878787"

# ========= Special Color =========
cursor = "#dad5c8"
correct = "#778777"
error = "#b07878"
hint = "#769494"
cancel = "#cc9393"
# Gradient color can only have two color!
gradient_color = ["#8e8b85", "#b4b0a7"]

# ========= File Panel Special Items =========
file_panel_top_directory_icon = "#b3ad9f"
file_panel_top_path = "#b3b3b3"
file_panel_item_selected_fg = "#9d9d9d"
file_panel_item_selected_bg = "#1e1e1e"

# ========= Sidebar Special Items =========
sidebar_title = "#b3b3b3"
sidebar_item_selected_fg = "#9d9d9d"
sidebar_item_selected_bg = "#1e1e1e"
sidebar_divider = "#414141"

# ========= Modal Special Items =========
modal_cancel_fg = "#414141"
modal_cancel_bg = "#cc9393"

modal_confirm_fg = "#414141"
modal_confirm_bg = "#9bb09b"

# ========= Help Menu =========
help_menu_hotkey = "#9bb09b"
help_menu_title = "#cc9393"
