[tools]
bun = "latest"
node = { version = "lts", postinstall = "corepack enable" }
python = "latest"

[tools."rust"]
version = "latest"
profile = "default"
targets = "x86_64-pc-windows-gnu" # aarch64-apple-darwin, x86_64-unknown-linux-gnu
