"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
show_hidden = true
linemode = "size_and_mtime"

[opener]
edit = [
  { run = '$EDITOR "$@"', block = true, for = "unix" },
  { run = "%EDITOR% %*", block = true, for = "windows" },
]

# 'spot' on a file to check it's mime-type with the default <Tab> key.
[open]
prepend_rules = [{ mime = "application/wine-extension-ini", use = "edit" }]
