# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  language: auto
  timeFormat: '02 Jan 06'
  shortTimeFormat: '3:04PM'
  showListFooter: true
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  showIcons: false
  nerdFontsVersion: '3'
  showFileIcons: true
  commitAuthorFormat: short # default: auto
  commitHashLength: 6 # default: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: arrowAndNumber
  commandLogSize: 8
  splitDiff: auto
  windowSize: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  filterMode: substring
  statusPanelView: dashboard
  authorColors:
    'noidilin': '#c0baad'
    '*': '#9a9487'
  theme:
    activeBorderColor: # Border color of focused window
      - '#c0baad'
      - bold
    inactiveBorderColor: # Border color of non-focused windows
      - '#878787'
    optionsTextColor: # Color of keybindings help text in the bottom line
      - '#4e4e4e'
    selectedLineBgColor: # Background color of selected line.
      - '#2a2a2a'
    cherryPickedCommitBgColor: # Background color of copied commit
      - '#414141'
    cherryPickedCommitFgColor: # Foreground color of copied commit
      - '#dad5c8'
    markedBaseCommitFgColor: # Foreground color of marked base commit (for rebase)
      - '#faf5eb'
    markedBaseCommitBgColor: # Background color of marked base commit (for rebase)
      - '#5d5d5d'
    unstagedChangesColor: # Color for file with unstaged changes
      - '#af5f5f'
    defaultFgColor: # Default text color
      - '#b3b3b3'
    searchingActiveBorderColor: # Border color of focused window when searching in that window
      - '#faf5eb'
      - bold

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
