# yaml-language-server: $schema=https://raw.githubusercontent.com/jesseduffield/lazygit/master/schema/config.json
gui:
  scrollHeight: 2
  scrollPastBottom: true
  scrollOffMargin: 2
  scrollOffBehavior: margin
  mouseEvents: true
  skipDiscardChangeWarning: false
  skipStashWarning: false
  skipNoStagedFilesWarning: false
  skipRewordInEditorWarning: false
  sidePanelWidth: 0.3333
  expandFocusedSidePanel: false
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible
  enlargedSideViewLocation: left
  language: auto
  timeFormat: '02 Jan 06'
  shortTimeFormat: '3:04PM'
  showListFooter: true
  showFileTree: true
  showRandomTip: true
  showCommandLog: true
  showBottomLine: true
  showPanelJumps: true
  showIcons: false
  nerdFontsVersion: '3'
  showFileIcons: true
  commitAuthorFormat: short # default: auto
  commitHashLength: 6 # default: 8
  showBranchCommitHash: false
  showDivergenceFromBaseBranch: arrowAndNumber
  commandLogSize: 8
  splitDiff: auto
  windowSize: normal
  border: rounded
  animateExplosion: true
  portraitMode: auto
  filterMode: substring
  statusPanelView: dashboard
  authorColors:
    'noidilin': '#c0baad'
    '*': '#9a9487'
  theme:
    activeBorderColor: # Border color of focused window
      - '#c0baad'
      - bold
    inactiveBorderColor: # Border color of non-focused windows
      - '#878787'
    searchingActiveBorderColor: # Border color of focused window when searching in that window
      - '#faf5eb'
      - bold
    optionsTextColor: # Color of keybindings help text in the bottom line
      - '#4e4e4e'
    selectedLineBgColor: # Background color of selected line.
      - '#2a2a2a'
    inactiveViewSelectedLineBgColor: # Background color of selected line when view doesn't have focus.
      - bold
    cherryPickedCommitFgColor: # Foreground color of copied commit
    - '#dad5c8'
    cherryPickedCommitBgColor: # Background color of copied commit
      - '#414141'
    markedBaseCommitFgColor: # Foreground color of marked base commit (for rebase)
      - '#faf5eb'
    markedBaseCommitBgColor: # Background color of marked base commit (for rebase)
      - '#5d5d5d'
    unstagedChangesColor: # Color for file with unstaged changes
      - red
    defaultFgColor: # Default text color
      - default # #b3b3b3
      - bold

# Keybindings
keybinding:
  # universal:
  #   quit: q
  #   quit-alt1: <c-c>
  #   return: <esc>
  #   quitWithoutChangingDirectory: Q
  #   togglePanel: <tab>
  #   prevItem: <up>
  #   nextItem: <down>
  #   prevItem-alt: k
  #   nextItem-alt: j
  #   prevPage: ','
  #   nextPage: .
  #   scrollLeft: H
  #   scrollRight: L
  #   gotoTop: <
  #   gotoBottom: '>'
  #   toggleRangeSelect: v
  #   rangeSelectDown: <s-down>
  #   rangeSelectUp: <s-up>
  #   prevBlock: <left>
  #   nextBlock: <right>
  #   prevBlock-alt: h
  #   nextBlock-alt: l
  #   nextBlock-alt2: <tab>
  #   prevBlock-alt2: <backtab>
  #   jumpToBlock:
  #     - "1"
  #     - "2"
  #     - "3"
  #     - "4"
  #     - "5"
  #   nextMatch: "n"
  #   prevMatch: "N"
  #   startSearch: /
  #   optionMenu: <disabled>
  #   optionMenu-alt1: '?'
  #   select: <space>
  #   goInto: <enter>
  #   confirm: <enter>
  #   confirmInEditor: <a-enter>
  #   remove: d
  #   new: "n"
  #   edit: e
  #   openFile: o
  #   scrollUpMain: <pgup>
  #   scrollDownMain: <pgdown>
  #   scrollUpMain-alt1: K
  #   scrollDownMain-alt1: J
  #   scrollUpMain-alt2: <c-u>
  #   scrollDownMain-alt2: <c-d>
  #   executeCustomCommand: ':'
  #   createRebaseOptionsMenu: m
  #
  #   # 'Files' appended for legacy reasons
  #   pushFiles: P
  #
  #   # 'Files' appended for legacy reasons
  #   pullFiles: p
  #   refresh: R
  #   createPatchOptionsMenu: <c-p>
  #   nextTab: ']'
  #   prevTab: '['
  #   nextScreenMode: +
  #   prevScreenMode: _
  #   undo: z
  #   redo: <c-z>
  #   filteringMenu: <c-s>
  #   diffingMenu: W
  #   diffingMenu-alt: <c-e>
  #   copyToClipboard: <c-o>
  #   openRecentRepos: <c-r>
  #   submitEditorText: <enter>
  #   extrasMenu: '@'
  #   toggleWhitespaceInDiffView: <c-w>
  #   increaseContextInDiffView: '}'
  #   decreaseContextInDiffView: '{'
  #   increaseRenameSimilarityThreshold: )
  #   decreaseRenameSimilarityThreshold: (
  #   openDiffTool: <c-t>

  # status:
  #   checkForUpdate: u
  #   recentRepos: <enter>
  #   allBranchesLogGraph: a
  
  # files:
  #   commitChanges: c
  #   commitChangesWithoutHook: w
  #   amendLastCommit: A
  #   commitChangesWithEditor: C
  #   findBaseCommitForFixup: <c-f>
  #   confirmDiscard: x
  #   ignoreFile: i
  #   refreshFiles: r
  #   stashAllChanges: s
  #   viewStashOptions: S
  #   toggleStagedAll: a
  #   viewResetOptions: D
  #   fetch: f
  #   toggleTreeView: '`'
  #   openMergeTool: M
  #   openStatusFilter: <c-b>
  #   copyFileInfoToClipboard: "y"

  # branches:
  #   createPullRequest: o
  #   viewPullRequestOptions: O
  #   copyPullRequestURL: <c-y>
  #   checkoutBranchByName: c
  #   forceCheckoutBranch: F
  #   rebaseBranch: r
  #   renameBranch: R
  #   mergeIntoCurrentBranch: M
  #   viewGitFlowOptions: i
  #   fastForward: f
  #   createTag: T
  #   pushTag: P
  #   setUpstream: u
  #   fetchRemote: f
  #   sortOrder: s

  # worktrees:
  #   viewWorktreeOptions: w

  commits:
  #   squashDown: s
  #   renameCommit: r
  #   renameCommitWithEditor: R
  #   viewResetOptions: g
  #   markCommitAsFixup: f
  #   createFixupCommit: F
  #   squashAboveCommits: S
    moveDownCommit: <c-d>
    moveUpCommit: <c-u>
  #   amendToCommit: A
  #   resetCommitAuthor: a
  #   pickCommit: p
  #   revertCommit: t
  #   cherryPickCopy: C
  #   pasteCommits: V
  #   markCommitAsBaseForRebase: B
  #   tagCommit: T
  #   checkoutCommit: <space>
  #   resetCherryPick: <c-R>
  #   copyCommitAttributeToClipboard: "y"
  #   openLogMenu: <c-l>
  #   openInBrowser: o
  #   viewBisectOptions: b
  #   startInteractiveRebase: i
  # amendAttribute:
  #   resetAuthor: a
  #   setAuthor: A
  #   addCoAuthor: c

  # stash:
  #   popStash: g
  #   renameStash: r

  # commitFiles:
  #   checkoutCommitFile: c

  # main:
  #   toggleSelectHunk: a
  #   pickBothHunks: b
  #   editSelectHunk: E

  # submodules:
  #   init: i
  #   update: u
  #   bulkMenu: b

  # commitMessage:
  #   commitMenu: <c-o>

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
